insert into employee(first_name, last_name, job_title, hired_date) values('Kaya', 'Murazik', 'Financial risk analyst', '2013-04-20');
insert into employee(first_name, last_name, job_title, hired_date) values('Myrl', 'Quitzon', 'Primary school teacher', '1998-01-07');
insert into employee(first_name, last_name, job_title, hired_date) values('Benito', 'Paucek', 'Museum/gallery curator', '2004-12-26');
insert into employee(first_name, last_name, job_title, hired_date) values('Blanche', 'Bayer', 'Community development worker', '2010-10-20');
insert into employee(first_name, last_name, job_title, hired_date) values('Rosie', 'Friesen', 'Higher education lecturer', '2010-12-30');
insert into employee(first_name, last_name, job_title, hired_date) values('Shauna', 'Schoen', 'Designer, fashion/clothing', '2004-08-05');
insert into employee(first_name, last_name, job_title, hired_date) values('Susann', 'Wisoky', 'Osteopath', '2011-05-19');
insert into employee(first_name, last_name, job_title, hired_date) values('Lindbergh', 'Quigley', 'Barrister', '2013-11-06');
insert into employee(first_name, last_name, job_title, hired_date) values('Redden', 'Grady', 'Adult nurse', '1998-05-20');
insert into employee(first_name, last_name, job_title, hired_date) values('Plummer', 'Hilpert', 'Gaffer', '2010-03-28');
insert into employee(first_name, last_name, job_title, hired_date) values('Marianita', 'Rogahn', 'Biomedical scientist', '2004-03-28');
insert into employee(first_name, last_name, job_title, hired_date) values('Tabetha', 'Kuphal', 'Prison officer', '2003-02-15');
insert into employee(first_name, last_name, job_title, hired_date) values('Selene', 'DuBuque', 'Copywriter, advertising', '2000-11-04');
insert into employee(first_name, last_name, job_title, hired_date) values('Matilda', 'O'Connell', 'Engineer, materials', '2004-02-28');
insert into employee(first_name, last_name, job_title, hired_date) values('Dora', 'Rippin', 'Engineer, maintenance (IT)', '2011-12-16');
insert into employee(first_name, last_name, job_title, hired_date) values('Candida', 'Green', 'Paediatric nurse', '2005-12-16');
insert into employee(first_name, last_name, job_title, hired_date) values('Claudine', 'Koepp', 'Scientific laboratory technician', '2001-06-30');
insert into employee(first_name, last_name, job_title, hired_date) values('Corbin', 'Reichert', 'Runner, broadcasting/film/video', '1999-06-10');
insert into employee(first_name, last_name, job_title, hired_date) values('Phebe', 'Wilderman', 'Theme park manager', '2004-12-13');
insert into employee(first_name, last_name, job_title, hired_date) values('Kate', 'Cremin', 'Engineer, aeronautical', '2011-11-30');
insert into project(project_name, deadline) values ('Project 1', '2016-09-06');
insert into project(project_name, deadline) values ('Project 2', '2017-04-08');
insert into project(project_name, deadline) values ('Project 3', '2017-03-04');
insert into project(project_name, deadline) values ('Project 4', '2017-05-21');
insert into project(project_name, deadline) values ('Project 5', '2016-11-19');
insert into project(project_name, deadline) values ('Project 6', '2017-04-19');
insert into project(project_name, deadline) values ('Project 7', '2017-01-30');
insert into project(project_name, deadline) values ('Project 8', '2016-08-28');
insert into project(project_name, deadline) values ('Project 9', '2017-03-11');
